[tool.poetry]
name = "facigrnotifications"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.12.0"
aiogram = "2.21"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

